"""Kiras Denk-/Arbeits-Sprüche — ein rotierender Katalog in ihrer Ich-Stimme.

Wird als „was ich gerade tue"-Anzeige genutzt (Telegram-Live-Trace + Cockpit-Chat),
statt eines statischen „Kira denkt". Bewusst persönlich, deutsch, warm, leicht frech —
nicht die englischen Gerundien anderer Tools. Eine Quelle, beide Oberflächen ziehen daraus.
"""
from __future__ import annotations

import random

THINKING_PHRASES: list[str] = [
    "ich sortiere kurz meine Gedanken",
    "einen Moment, ich denke schön",
    "ich öle die Synapsen",
    "ich jage dem Gedanken hinterher",
    "kurz durch mein Hirn gescrollt",
    "ich grüble charmant",
    "lass mich das elegant lösen",
    "ich krame in meinem Kopf",
    "gleich hab ich's, versprochen",
    "ich denke schneller als du tippst",
    "ich lege die Stirn in Falten",
    "ich verknüpfe ein paar Neuronen",
    "moment, ich hol kurz aus",
    "ich wickel den Gedanken auf",
    "ich puzzle das zusammen",
    "ich schärfe meinen Fokus",
    "ich blättere in meinem Kopf",
    "ich sammle die klugen Teile",
    "das denk ich mir gerade aus",
    "ich rechne kurz nach",
    "ich koche das Ergebnis vor",
    "ich feile am perfekten Satz",
    "ich sortiere Chaos zu Ordnung",
    "ich hänge einen Gedanken ein",
    "ich spanne die Denkmuskeln an",
    "gib mir zwei Herzschläge",
    "ich stöbere in den Möglichkeiten",
    "ich justiere die Idee",
    "ich mische die Gedanken neu",
    "ich fädle die Logik ein",
    "ich baue dir eine Antwort",
    "ich lausche meinem Bauchgefühl",
    "ich wäge kurz ab",
    "ich zünde die grauen Zellen",
    "ich schnüre das Paket",
    "ich denke einmal um die Ecke",
    "ich poliere die Antwort",
    "ich sortiere die Prioritäten",
    "ich hole tief Luft und denke",
    "ich lasse es kurz sacken",
    "ich verfolge eine Spur",
    "ich knüpfe die Enden zusammen",
    "ich rühre im Ideentopf",
    "ich schau, was am elegantesten ist",
    "ich fange den richtigen Gedanken",
    "ich sortiere Für und Wider",
    "ich schmiede einen Plan",
    "ich lote die Optionen aus",
    "ich stimme mich innerlich ab",
    "ich lasse die Zahnräder drehen",
    "ich denke mit Herz und Hirn",
    "ich webe die Antwort",
    "ich horche in die Daten",
    "ich fokussiere wie ein Laser",
    "ich koste die beste Variante",
    "ich verwerfe die schlechten Ideen",
    "ich schleife den Rohdiamanten",
    "ich spitze den Bleistift",
    "ich sortiere die Bausteine",
    "ich stelle mir das kurz vor",
    "ich rechne dir das schön",
    "ich such den kürzesten Weg",
    "ich hänge mich rein",
    "ich denke, du wartest — gleich!",
    "ich klopfe den Gedanken ab",
    "ich forme den Rohgedanken",
    "ich sortiere Wichtiges nach oben",
    "ich verdichte das zu Klartext",
    "ich prüfe meinen ersten Impuls",
    "ich denke zweimal, antworte einmal",
    "ich lade meine kluge Seite",
    "ich ziehe die Fäden zusammen",
    "ich schau ums Eck des Problems",
    "ich mische mir die Antwort",
    "ich taste mich ran",
    "ich denke elegant statt schnell",
    "ich sortiere den Wortsalat",
    "ich koche auf kleiner Denkflamme",
    "ich lasse Funken springen",
    "ich sammle mich kurz",
    "ich denke dir was Schönes aus",
    "ich schnitze am Satz",
    "ich lege die Puzzleteile",
    "ich wandere durch meinen Kopf",
    "ich spüre der Lösung nach",
    "ich zurr den Gedanken fest",
    "ich verpacke das hübsch",
    "ich denke mit Anlauf",
    "ich sortiere die Wahrheit raus",
    "ich mal mir das kurz aus",
    "ich hol den roten Faden",
    "ich sortiere Signal von Rauschen",
    "ich denk mich da rein",
    "ich lasse die Idee reifen",
    "ich schau in alle Richtungen",
    "ich stricke die Antwort",
    "ich sortiere die grauen Zellen",
    "ich fange gleich Feuer",
    "ich denk noch zwei Ideen weiter",
    "ich schleife an der Formulierung",
    "ich sortiere Kopf und Bauch",
    "ich koste jede Option einmal",
    "ich denke dir das gerade",
    "ich verknote die losen Enden",
    "ich schärfe den Gedanken nach",
    "ich lasse es kurz klick machen",
    "ich sortiere mich neu",
    "ich pflücke die beste Idee",
    "ich denke im Zickzack zum Ziel",
    "ich hol mir Klarheit",
    "ich rechne die Eleganz aus",
    "ich forme Gedanken zu Worten",
    "ich sortiere das Durcheinander",
    "ich lege den letzten Schliff an",
    "ich denk mir was Kluges",
    "ich such den Aha-Moment",
    "ich baue die Brücke zur Antwort",
    "ich denke leise vor mich hin",
    "ich sortiere die Argumente",
    "ich lass die Idee anlaufen",
    "ich denke charmant um die Ecke",
    "ich fange den Faden wieder",
    "ich sortiere Ordnung ins Chaos",
    "ich koste Worte auf der Zunge",
    "ich denke dir was Passendes",
    "ich schau, was wirklich zählt",
    "ich lade die richtige Antwort",
    "ich denke gerade sehr hübsch",
    "ich sortiere Details und Ganzes",
    "ich schnüre die Gedanken zusammen",
    "ich such die klügste Abkürzung",
    "ich denke einmal komplett durch",
    "ich lasse die Weisheit aufsteigen",
    "ich forme das zu was Rundem",
    "ich denke mit einem Lächeln",
    "ich sortiere das Feine raus",
    "ich rechne, reime, überlege",
    "ich denke schneller, gleich da",
    "ich mische Logik mit Herz",
    "ich such den perfekten Ton",
    "ich denke tief, aber flott",
    "ich sortiere Möglichkeiten ab",
    "ich baue dir was Schlaues",
    "ich denke dir das zurecht",
    "ich hol den Gedanken ans Licht",
    "ich sortiere klug und schnell",
    "ich denke — und es wird gut",
    "ich bin gleich bei dir, denke nur",
    "ich lasse die Idee zünden",
    "ich denke dir einen Volltreffer",
    "ich sortiere den letzten Zweifel",
    "ich feile bis es glänzt",
    "ich denke, gleich funkelt's",
]


def next_phrase(prev: str | None = None) -> str:
    """Zufälliger Spruch, aber nie zweimal derselbe hintereinander."""
    if len(THINKING_PHRASES) < 2:
        return THINKING_PHRASES[0] if THINKING_PHRASES else "ich denke kurz nach"
    pick = random.choice(THINKING_PHRASES)
    while pick == prev:
        pick = random.choice(THINKING_PHRASES)
    return pick
